CREATE TABLE [Current Period] (
    [Time] DATETIME,
    [Vertical Subset Except Default] varchar(50),
    [Planned Not Hire Position] varchar(50),
    [Position Start Date] DATETIME,
    [First Hire Date] DATETIME,
    [Employee ID] varchar(50),
    [Employee Hired Date] DATETIME,
    [Hired Effective Date] DATETIME,
    [TA Open Hold Date] DATETIME,
    [TA Offered] varchar(50),
    [Final Date] DATETIME,
    [Strategy 2 0] varchar(50),
    [Planned Not Hired (Positions)] int,
    [Planned Not Hired Amount (USD)] FLOAT,
    [Total Days Lost] int,
    [Avg Days Lost per Employee] int,
    [Planned Not Hired - Strategy 2 0 (Positions)] int,
    [Planned Not Hired Amount - Strategy 2 0 Positions (USD)] int,
    [Total Days Lost- Strategy 2 0 Positions] int,
    [Avg Days Lost per Employee- Strategy 2 0 Position] int,
    [Planned Not Hired Position - All Position] int,
    [Planned Not Hired Amount - All Position] int,
    [Plan Yet Open] varchar(50),
    [Strategy 2 0 Skills] varchar(50),
    [Vertical] varchar(50),
    [Grp Hierarchy Vertical] varchar(50),
    [Check] varchar(50),
    [Current Period] DATETIME,
    [---Test---] varchar(50),
    [Current Headcount] int,
    [AOP Vacant Positions] int,
    [TA Open] varchar(50),
    [Attrition %] varchar(50),
    [Attrition Backfills] varchar(50),
    [Sub Grp Vertical] varchar(50)
)