CREATE TABLE [Simulation - CY] (
    [Time] DATETIME,
    [Report Type] varchar(50),
    [Anaplan ID] varchar(50),
    [Report Type_] varchar(50),
    [To Export for BI - One Time Load] varchar(50),
    [Promo-In Changed Position ID] varchar(50),
    [Wrong Promo Identifier] INT,
    [Transferred Last Mapped ID of Rectified ID] varchar(50),
    [Mapping History] varchar(50),
    [Final Sub Band of Position] varchar(50),
    [Promo-Changed Sub Band] varchar(50),
    [Promo Out Date] DATETIME,
    [Promo-In Effective Date] DATETIME,
    [Promo-In Position ID] varchar(50),
    [Clear Promo] varchar(50),
    [Org  Position Sub-Band] varchar(50),
    [AID] varchar(50),
    [Simulation Tag] varchar(50),
    [Select for Simulation] varchar(50),
    [Simulation Effective Date] DATETIME,
    [Full Name] varchar(50),
    [Position ID] varchar(50),
    [Position ID (WFS)] varchar(50),
    [Position Sub Band] varchar(50),
    [Position Job Family] varchar(50),
    [Position Country] varchar(50),
    [Employee ID] varchar(50),
    [Start Date] DATETIME,
    [LWD] DATETIME,
    [T-Job Req ID Against PID] varchar(50),
    [JR ID] varchar(50),
    [JR Status] varchar(50),
    [Status] varchar(50),
    [Gender] varchar(50),
    [Raised JR ID] varchar(50),
    [Sub Vertical] varchar(50),
    [BU SSU] varchar(50),
    [LOB Segment] varchar(50),
    [Vertical] varchar(50),
    [Entity] varchar(50),
    [Employee Sub Band] varchar(50),
    [Facility  Country] varchar(50),
    [Cost Center] varchar(50),
    [Job Level] varchar(50),
    [Job Family] varchar(50),
    [Job Family Cluster] varchar(50),
    [City Cluster] varchar(50),
    [International Region] varchar(50),
    [Facility] varchar(50),
    [Geozone] varchar(50),
    [Reporting Manager ID] varchar(50),
    [Reporting Manager] varchar(50),
    [Job Code Description] varchar(50),
    [Designation] varchar(50),
    [MIS Cost Center] varchar(50),
    [Post Tag Cost Center] varchar(50),
    [Position End Date] DATETIME,
    [Variable Pay Plan Type] varchar(50),
    [Employee Class] varchar(50),
    [Internal Specialization Name] varchar(50),
    [Current Quartile Position] varchar(50),
    [Revised Quartile] varchar(50),
    [Stack Rank Current] varchar(50),
    [Stack Rank - Planned] varchar(50),
    [Stack Rank Final] varchar(50),
    [Software Defined Networking (SDN)] varchar(50),
    [Mobility] varchar(50),
    [Cloud Enabled Solution] varchar(50),
    [Digitization (Robotics, Software, Analytics, Big Data)] varchar(50),
    [Partnering (Service Co-creation, GTM, Supply Chain Mgmt )] varchar(50),
    [Local Currency] varchar(50),
    [FIXPAY-Amount] INT,
    [RETIRALS-Amount] INT,
    [Tata Group Joining Group] varchar(50),
    [Increment %] FLOAT,
    [Increment Override] FLOAT,
    [Check For Zero Increment] varchar(50),
    [OTE-(HeadCount Offered)] INT,
    [OTE (Local Currency)] INT,
    [OTE After Increment] FLOAT,
    [Fringes (Local Currency)] INT,
    [Loaded Cost (Local Currency)] FLOAT,
    [FIXPAY-Amount  US $] FLOAT,
    [RETIRALS-Amount  US $] FLOAT,
    [VARPAY-Amount  US $] FLOAT,
    [OTE (USD)] FLOAT,
    [Fringes (USD)] FLOAT,
    [Loaded Cost (USD)] FLOAT,
    [Final Effective Date] DATETIME,
    [Effective Start Date] DATETIME,
    [Override Effective Start Date] DATETIME,
    [New Manager ID] varchar(50),
    [Existing Manager] varchar(50),
    [Final Manager For Span of Control] varchar(50),
    [Post Tag Country] varchar(50),
    [Post Tag Job Family] varchar(50),
    [Post Tag Sub Band] varchar(50),
    [Post Tag Currency (Local)] varchar(50),
    [Post Tag OTE (in Local Currency)] varchar(50),
    [Post Tag OTE Override (Local Currency)] varchar(50),
    [Post Tag Fringes (in Local Currency)] varchar(50),
    [Post Tag OTE (USD)] varchar(50),
    [Post Tag Fringes (USD)] varchar(50),
    [Prospective Outlook (CY) USD] FLOAT,
    [Cost] FLOAT,
    [Cost with Lever Intermediary] varchar(50),
    [Cost with Lever breakup] varchar(50),
    [Promo in Employee Subband] varchar(50),
    [Promo in Employee AID] varchar(50),
    [Ana ID Code of Promo In Emp] varchar(50),
    [Promo-In Employee ID] varchar(50),
    [Strategy 2 0 Skills] varchar(50),
    [Counts] INT,
    [Unique Code Quartile] varchar(50),
    [Final Band] varchar(50),
    [Final Country] varchar(50),
    [Final Job Family] varchar(50),
    [Final Currency] varchar(50),
    [Outlook-HC] INT,
    [FY Exit HC] INT,
    [CTC $ - FY Exit] FLOAT,
    [AVG HC] INT,
    [Position Count in HC] INT,
    [Final End Date] DATETIME,
    [Check For Simulation] varchar(50),
    [Test Ana ID] varchar(50),
    [Quartile Count] INT,
    [Total] INT,
    [AOP Headcount] INT,
    [Female] INT,
    [Active Churn Count] INT,
    [Active Churn Cost] INT,
    [FY EXIT YTD] INT,
    [Position END - Promotion] INT,
    [Position Vacant] INT,
    [Lever Used] INT,
    [Wrong Lever] INT,
    [Final Version] INT,
    [HC Exist against AOP] INT,
    [Occupied By HC] INT,
    [Occupied By JR Offered] INT,
    [Opening For Promotion] INT,
    [Promo Out ] INT,
    [Promo IN ] INT,
    [NA For Promotion] INT,
    [Available for Promotion] varchar(50),
    [Available for Promotion On] varchar(50),
    [Promotion Flag] varchar(50),
    [Error C F Tag] varchar(50),
    [Conditional Formatting Flag] varchar(50),
    [Reason (If Error in Simulation Tag)] varchar(50),
    [Date Flag] varchar(50),
    [Band Rank ] varchar(50),
    [BU Code] varchar(50),
    [LOB Code] varchar(50),
    [VERTICAL Code] varchar(50),
    [Position Start Date] DATETIME,
    [Levers Counts] varchar(50),
    [AOP Budgeted Cost] varchar(50),
    [Low Cost - Total cost] FLOAT,
    [High Cost - Total cost] FLOAT,
    [Low Cost - Headcount] int,
    [High cost - Headcount] varchar(50),
    [Parent Country] varchar(50),
    [(Final Country)] varchar(50),
    [(Cost Center)] varchar(50),
    [(Sub Band)] varchar(50),
    [bu] varchar(50),
    [Unique DFM Code] varchar(50),
    [Test - DFM Ind  HC] varchar(50),
    [Test - DFM Int  HC] varchar(50),
    [Test - DFM Low Cost] FLOAT,
    [Test - DFM High Cost] varchar(50),
    [Balanced AOP SLA] varchar(50),
    [HC Count ] varchar(50),
    [HC-HC] varchar(50),
    [LC-EXIT] FLOAT,
    [HC-EXIT] FLOAT,
    [Offered Female] varchar(50),
    [Promo-IN Count] varchar(50),
    [Parent Position ID] varchar(50),
    [Parent of Position ID] varchar(50),
    [Emp  for country] varchar(50),
    [Anaplan Code] varchar(50),
    [Outlook-cost] FLOAT,
    [JR Tag] varchar(50),
    [position count] varchar(50),
    [FY Exit OTE] INT,
    [FY Exit Sub-Band] varchar(50),
    [FY Exit Country] varchar(50),
    [FY Exit Currency] varchar(50),
    [AOP-Increment % with increment FY Exc  Rate] FLOAT,
    [AOP-Increment Override % with increment FY Exc  Rate] varchar(50),
    [Outlook Cost Variation] varchar(50),
    [Filter View] varchar(50),
    [Overall Balance   Open   Offered Position] varchar(50),
    [Outlook Annualized Cost] FLOAT,
    [Dashboard 3 Cost] varchar(50),
    [Previous Employee ID] varchar(50),
    [Current Period] varchar(50),
    [Check] varchar(50),
    [New Hire CY Cal] varchar(50),
    [User-Matrix BU] varchar(50),
    [User-Matrix LOB] varchar(50),
    [User-Matrix Vertical] varchar(50),
    [Region] varchar(50),
    [Job Family Cluster Count] INT,
    [Job Family Cluster Cost] FLOAT,
    [(Final Cost Center) Test] varchar(50),
    [OTE(USD)] varchar(50),
    [DFM Fringes Low Cost] varchar(50),
    [DFM Fringes High Cost] varchar(50),
    [DFM OTE Low Cost] FLOAT,
    [DFM OTE High Cost] varchar(50),
    [MIS items] varchar(50),
    [Check Version] varchar(50),
    [City Cluster_HC] varchar(50),
    [Cost Tag] varchar(50),
    [DFM High Cost] varchar(50),
    [DFM Ind  HC] varchar(50),
    [DFM Int  HC] varchar(50),
    [DFM Low Cost] FLOAT,
    [Eligible for inc] varchar(50),
    [Final Facility-AOP] varchar(50),
    [Final Facility-Outlook] varchar(50),
    [Fringes ] FLOAT,
    [Job family Cluster HC] varchar(50),
    [LC-HC] varchar(50),
    [New Hire CY] varchar(50),
    [Post Tag Facility] varchar(50),
    [Post Tag Entity] varchar(50),
    [Role Matrix] varchar(50),
    [VARPAY-Amount] INT,
    [Position ID for Overlapping] varchar(50),
    [Position Count for Actual Cost] varchar(50),
    [Position Overlapping (Transition)] varchar(50),
    [BU for Geographical Selection] varchar(50),
    [Job Family Cluster for Geographical Selection] varchar(50),
    [Job Family Cluster for Geographical Selection_HC] varchar(50),
    [Promo-In Position ID (AOP - FY)] varchar(50),
    [Clear Promo (AOP - FY)] varchar(50),
    [Simulation Tag (AOP - FY)] varchar(50),
    [Select for Simulation (AOP - FY)] varchar(50),
    [Position Sub Band (AOP - FY)] varchar(50),
    [Start Date (AOP - FY)] DATETIME,
    [Facility Country (AOP - FY)] varchar(50),
    [Cost Center (AOP - FY)] varchar(50),
    [OTE-(HeadCount Offered) (AOP - FY)] INT,
    [Loaded Cost (USD) (AOP - FY)] FLOAT,
    [Cost (AOP - FY)] varchar(50),
    [Conditional Formatting Flag (AOP - FY)] varchar(50),
    [Counts (AOP - FY)] varchar(50),
    [Levers Counts (AOP - FY)] varchar(50),
    [AOP Budgeted Cost (AOP - FY)] varchar(50),
    [Low Cost - Headcount (AOP - FY)] varchar(50),
    [High cost - Headcount (AOP - FY)] varchar(50),
    [(Final Country) (AOP - FY)] varchar(50),
    [def country (AOP - FY)] varchar(50),
    [(Cost Center) (AOP - FY)] FLOAT,
    [(Sub Band) (AOP - FY)] varchar(50),
    [Budgeted Position (AOP - FY)] varchar(50),
    [DFM Low Cost (AOP - FY)] FLOAT,
    [DFM High Cost (AOP - FY)] FLOAT,
    [New Hire Tag (AOP - FY)] varchar(50),
    [NH Counts (AOP - FY)] varchar(50),
    [NH Cost (AOP - FY)] FLOAT,
    [Growth Business NH Count (AOP - FY)] varchar(50),
    [Growth Business NH Cost (AOP - FY)] FLOAT,
    [OTE Local without Increment  CY Exc  Rate (AOP - FY)] varchar(50),
    [Benefits Local without Increment  CY Exc  Rate (AOP - FY)] varchar(50),
    [Load cost USD without Increment  CY Exc  Rate (AOP - FY)] FLOAT,
    [Cost column without Increment  CY Exc  Rate (AOP - FY)] FLOAT,
    [Local OTE Post Increment%  with  CY Exc Rate (AOP - FY)] varchar(50),
    [Benefits Local with Increment  CY Exc  Rate (AOP - FY)] varchar(50),
    [Load cost USD  with Increment  CY Exc  Rate (AOP - FY)] FLOAT,
    [Cost column  with Increment  CY Exc  Rate (AOP - FY)] FLOAT,
    [Local OTE Post Increment%  with  FY Exc Rate (AOP - FY)] varchar(50),
    [Benefits Local with increment FY Exc  Rate (AOP - FY)] varchar(50),
    [Load cost USD with increment FYExc  Rate (AOP - FY)] FLOAT,
    [OTE After Lever (AOP - FY)] varchar(50),
    [Benefits After Lever (AOP - FY)] varchar(50),
    [Loaded Cost (USD) After Lever (AOP - FY)] FLOAT,
    [AOP FY EXIT HC (AOP - FY)] varchar(50),
    [AOP FY EXIT COST (AOP - FY)] FLOAT,
    [AOP FY Count (AOP - FY)] varchar(50),
    [AOP FY OTE (AOP - FY)] varchar(50),
    [AOP FY Benefits (AOP - FY)] varchar(50),
    [NH Band (AOP - FY)] varchar(50),
    [AOP FY Year (AOP - FY)] DATETIME,
    [AOP FY Sub Band (AOP - FY)] varchar(50),
    [Total Varriable pay (AOP - FY)] varchar(50),
    [Basic Salary (AOP - FY)] varchar(50),
    [RETRIALS (AOP - FY)] varchar(50),
    [Period for Fixed pay (AOP - FY)] varchar(50),
    [allowance (AOP - FY)] FLOAT,
    [HRA (AOP - FY)] varchar(50),
    [Statutory Bonus (AOP - FY)] varchar(50),
    [Fixed Salary (AOP - FY)] varchar(50),
    [Promo Changed Sub Band  (AOP - FY)] varchar(50),
    [AOP FY Country (AOP - FY)] varchar(50),
    [AOP FY Currency (AOP - FY)] varchar(50),
    [Band For Fixed Sal IND (AOP - FY)] varchar(50),
    [Band For Fixed Sal INT (AOP - FY)] varchar(50),
    [%deduction in Variable (AOP - FY)] varchar(50),
    [Total varriable pay before lever (AOP - FY)] varchar(50),
    [Budgeted CTC after lever (AOP - FY)] FLOAT,
    [Budgeted CTC before lever (AOP - FY)] FLOAT,
    [New Hire CY Cal (AOP - FY)] varchar(50),
    [MIS Items (AOP - FY)] varchar(50),
    [Position AOP End Date (AOP - FY)] DATETIME,
    [Position AOP Start Date (AOP - FY)] DATETIME,
    [Actual Start Date of Position (AOP - FY)] DATETIME,
    [Post Tag Entity (AOP - FY)] varchar(50),
    [Attrition Replacement] varchar(50),
    [Final Sub Band of Position (AOP - FY)] varchar(50),
    [Employee Sub Band (AOP - FY)] varchar(50),
    [International Region (AOP - FY)] varchar(50),
    [Revised Quartile (AOP - FY)] varchar(50),
    [Local Currency (AOP - FY)] varchar(50),
    [OTE (Local Currency) (AOP - FY)] varchar(50),
    [Fringes (Local Currency) (AOP - FY)] varchar(50),
    [Loaded Cost (Local Currency) (AOP - FY)] FLOAT,
    [Prospective Outlook (CY) USD (AOP - FY)] varchar(50),
    [Cost with Lever Intermediary (AOP - FY)] FLOAT,
    [Cost with Lever breakup (AOP - FY)] FLOAT,
    [Unique Code Quartile (AOP - FY)] varchar(50),
    [Final End Date (AOP - FY)] DATETIME,
    [Lever Used (AOP - FY)] varchar(50),
    [Low Cost - Total cost (AOP - FY)] FLOAT,
    [High Cost - Total cost (AOP - FY)] FLOAT,
    [Parent Country (AOP - FY)] varchar(50),
    [DFM Ind  HC (AOP - FY)] varchar(50),
    [DFM Int  HC (AOP - FY)] varchar(50),
    [Vertical (AOP - FY)] varchar(50),
    [Job Level (AOP - FY)] varchar(50),
    [OTE After Increment (AOP - FY)] varchar(50),
    [OTE (USD) (AOP - FY)] varchar(50),
    [Fringes (USD) (AOP - FY)] varchar(50),
    [Promo in Employee Subband (AOP - FY)] varchar(50),
    [Balanced AOP SLA (AOP - FY)] varchar(50),
    [LOB Segment (AOP - FY)] varchar(50),
    [BU SSU (AOP - FY)] varchar(50)
)