drop table Simulation_1;
CREATE TABLE [Simulation_1] (
    [Time] nvarchar(15),
    [Report Type] nvarchar(100),
    [Anaplan ID] varchar(max),
    [To Export for BI - One Time Load] nvarchar(100),
    [Report Type_] nvarchar(100),
    [Promo-In Changed Position ID] nvarchar(100),
    [Wrong Promo Identifier] nvarchar(20),
    [Transferred Last Mapped ID of Rectified ID] nvarchar(100),
    [Mapping History] nvarchar(100),
    [Final Sub Band of Position] nvarchar(100),
    [Promo-Changed Sub Band] nvarchar(100),
    [Promo Out Date] DATETIME,
    [Promo-In Effective Date] DATETIME,
    [Promo-In Position ID] nvarchar(100),
    [Clear Promo] nvarchar(100),
    [Org  Position Sub-Band] nvarchar(100),
    [AID] nvarchar(100),
    [Simulation Tag] nvarchar(100),
    [Select for Simulation] nvarchar(100),
    [Simulation Effective Date] DATETIME,
    [Full Name] nvarchar(100),
    [Position ID] nvarchar(100),
    [Position ID (WFS)] nvarchar(100),
    [Position Sub Band] nvarchar(100),
    [Position Job Family] nvarchar(100),
    [Position Country] nvarchar(100),
    [Employee ID] nvarchar(100),
    [Start Date] DATETIME,
    [LWD] DATETIME,
    [T-Job Req ID Against PID] nvarchar(100),
    [JR ID] nvarchar(100),
    [JR Status] nvarchar(100),
    [Status] nvarchar(100),
    [Gender] nvarchar(100),
    [Raised JR ID] nvarchar(100),
    [Sub Vertical] nvarchar(100),
    [BU SSU] nvarchar(100),
    [LOB Segment] nvarchar(100),
    [Vertical] nvarchar(100),
    [Entity] varchar(100),
    [Employee Sub Band] nvarchar(100),
    [Facility  Country] nvarchar(100),
    [Cost Center] nvarchar(100),
    [Job Level] nvarchar(100),
    [Job Family] nvarchar(100),
    [Job Family Cluster] nvarchar(100),
    [City Cluster] nvarchar(100),
    [International Region] nvarchar(100),
    [Facility] nvarchar(100),
    [Geozone] nvarchar(100),
    [Reporting Manager ID] nvarchar(100),
    [Reporting Manager] nvarchar(100),
    [Job Code Description] nvarchar(100),
    [Designation] nvarchar(100),
    [MIS Cost Center] nvarchar(100),
    [Post Tag Cost Center] nvarchar(100),
    [Position End Date] DATETIME,
    [Variable Pay Plan Type] nvarchar(100),
    [Employee Class] nvarchar(100),
    [Internal Specialization Name] nvarchar(100),
    [Current Quartile Position] nvarchar(100),
    [Revised Quartile] nvarchar(100),
    [Stack Rank Current] nvarchar(100),
    [Stack Rank - Planned] nvarchar(100),
    [Stack Rank Final] nvarchar(100),
    [Software Defined Networking (SDN)] nvarchar(100),
    [Mobility] nvarchar(100),
    [Cloud Enabled Solution] nvarchar(100),
    [Digitization (Robotics, Software, Analytics, Big Data)] nvarchar(100),
    [Partnering (Service Co-creation, GTM, Supply Chain Mgmt )] nvarchar(100),
    [Local Currency] nvarchar(100),
    [FIXPAY-Amount] nvarchar(20),
    [RETIRALS-Amount] nvarchar(20),
    [Tata Group Joining Group] nvarchar(100),
    [Increment %] FLOAT,
    [Increment Override] FLOAT,
    [Check For Zero Increment] nvarchar(100),
    [OTE-(HeadCount Offered)] nvarchar(20),
    [OTE (Local Currency)] nvarchar(20),
    [OTE After Increment] FLOAT,
    [Fringes (Local Currency)] nvarchar(20),
    [Loaded Cost (Local Currency)] FLOAT,
    [FIXPAY-Amount  US $] FLOAT,
    [RETIRALS-Amount  US $] FLOAT,
    [VARPAY-Amount  US $] nvarchar(20),
    [OTE (USD)] FLOAT,
    [Fringes (USD)] FLOAT,
    [Loaded Cost (USD)] FLOAT,
    [Final Effective Date] DATETIME,
    [Effective Start Date] DATETIME,
    [Override Effective Start Date] DATETIME,
    [New Manager ID] nvarchar(100),
    [Existing Manager] nvarchar(100),
    [Final Manager For Span of Control] nvarchar(100),
    [Post Tag Country] nvarchar(100),
    [Post Tag Job Family] nvarchar(100),
    [Post Tag Sub Band] nvarchar(100),
    [Post Tag Currency (Local)] nvarchar(100),
    [Post Tag OTE (in Local Currency)] nvarchar(100),
    [Post Tag OTE Override (Local Currency)] nvarchar(100),
    [Post Tag Fringes (in Local Currency)] nvarchar(100),
    [Post Tag OTE (USD)] nvarchar(100),
    [Post Tag Fringes (USD)] nvarchar(100),
    [Prospective Outlook (CY) USD] FLOAT,
    [Cost] FLOAT,
    [Cost with Lever Intermediary] nvarchar(100),
    [Cost with Lever breakup] nvarchar(100),
    [Promo in Employee Subband] nvarchar(100),
    [Promo in Employee AID] nvarchar(100),
    [Ana ID Code of Promo In Emp] nvarchar(100),
    [Promo-In Employee ID] nvarchar(100),
    [Strategy 2 0 Skills] nvarchar(100),
    [Counts] nvarchar(20),
    [Unique Code Quartile] nvarchar(100),
    [Final Band] nvarchar(100),
    [Final Country] nvarchar(100),
    [Final Job Family] nvarchar(100),
    [Final Currency] nvarchar(100),
    [Outlook-HC] nvarchar(20),
    [FY Exit HC] nvarchar(20),
    [CTC $ - FY Exit] FLOAT,
    [AVG HC] nvarchar(20),
    [Position Count in HC] nvarchar(20),
    [Final End Date] DATETIME,
    [Check For Simulation] nvarchar(100),
    [Test Ana ID] nvarchar(100),
    [Quartile Count] nvarchar(20),
    [Total] nvarchar(20),
    [AOP Headcount] nvarchar(20),
    [Female] nvarchar(20),
    [Active Churn Count] nvarchar(20),
    [Active Churn Cost] nvarchar(20),
    [FY EXIT YTD] nvarchar(20),
    [Position END - Promotion] nvarchar(20),
    [Position Vacant] nvarchar(20),
    [Lever Used] nvarchar(20),
    [Wrong Lever] nvarchar(20),
    [Final Version] nvarchar(20),
    [HC Exist against AOP] nvarchar(20),
    [Occupied By HC] nvarchar(20),
    [Occupied By JR Offered] nvarchar(20),
    [Opening For Promotion] nvarchar(20),
    [Promo Out ] nvarchar(20),
    [Promo IN ] nvarchar(20),
    [NA For Promotion] nvarchar(20),
    [Available for Promotion] nvarchar(100),
    [Available for Promotion On] nvarchar(100),
    [Promotion Flag] nvarchar(100),
    [Error C F Tag] nvarchar(100),
    [Conditional Formatting Flag] nvarchar(100),
    [Reason (If Error in Simulation Tag)] nvarchar(100),
    [Date Flag] nvarchar(100),
    [Band Rank ] nvarchar(100),
    [BU Code] nvarchar(100),
    [LOB Code] nvarchar(100),
    [VERTICAL Code] nvarchar(100),
    [Position Start Date] DATETIME,
    [Levers Counts] nvarchar(100),
    [AOP Budgeted Cost] nvarchar(100),
    [Low Cost - Total cost] FLOAT,
    [High Cost - Total cost] FLOAT,
    [Low Cost - Headcount] nvarchar(20),
    [High cost - Headcount] nvarchar(100),
    [Parent Country] nvarchar(100),
    [(Final Country)] nvarchar(100),
    [(Cost Center)] nvarchar(100),
    [(Sub Band)] nvarchar(100),
    [bu] nvarchar(100),
    [Unique DFM Code] nvarchar(100),
    [Test - DFM Ind  HC] nvarchar(100),
    [Test - DFM Int  HC] nvarchar(100),
    [Test - DFM Low Cost] FLOAT,
    [Test - DFM High Cost] nvarchar(100),
    [Balanced AOP SLA] nvarchar(100),
    [HC Count ] nvarchar(100),
    [HC-HC] nvarchar(100),
    [LC-EXIT] FLOAT,
    [HC-EXIT] FLOAT,
    [Offered Female] nvarchar(100),
    [Promo-IN Count] nvarchar(100),
    [Parent Position ID] nvarchar(100),
    [Parent of Position ID] nvarchar(100),
    [Emp  for country] nvarchar(100),
    [Anaplan Code] nvarchar(100),
    [Outlook-cost] FLOAT,
    [JR Tag] nvarchar(100),
    [position count] nvarchar(100),
    [FY Exit OTE] nvarchar(20),
    [FY Exit Sub-Band] nvarchar(100),
    [FY Exit Country] nvarchar(100),
    [FY Exit Currency] nvarchar(100),
    [AOP-Increment % with increment FY Exc  Rate] FLOAT,
    [AOP-Increment Override % with increment FY Exc  Rate] nvarchar(100),
    [Outlook Cost Variation] nvarchar(100),
    [Filter View] nvarchar(100),
    [Overall Balance   Open   Offered Position] nvarchar(100),
    [Outlook Annualized Cost] FLOAT,
    [Dashboard 3 Cost] nvarchar(100),
   [Previous Employee ID] nvarchar(100),
    [Current Period] nvarchar(100),
    [Check] nvarchar(100),
    [New Hire CY Cal] nvarchar(100),
    [User-Matrix BU] nvarchar(100),
    [User-Matrix LOB] nvarchar(100),
    [User-Matrix Vertical] nvarchar(100),
    [Region] nvarchar(100),
    [Job Family Cluster Count] nvarchar(20),
    [Job Family Cluster Cost] FLOAT,
    [(Final Cost Center) Test] nvarchar(100),
    [OTE(USD)] nvarchar(100),
    [DFM Fringes Low Cost] nvarchar(100),
    [DFM Fringes High Cost] nvarchar(100),
    [DFM OTE Low Cost] FLOAT,
    [DFM OTE High Cost] nvarchar(100),
    [MIS items] nvarchar(100),
    [Check Version] nvarchar(100),
    [City Cluster_HC] nvarchar(100),
    [Cost Tag] nvarchar(100),
    [DFM High Cost] nvarchar(100),
    [DFM Ind  HC] nvarchar(100),
    [DFM Int  HC] nvarchar(100),
    [DFM Low Cost] FLOAT,
    [Eligible for inc] nvarchar(100),
    [Final Facility-AOP] nvarchar(100),
    [Final Facility-Outlook] nvarchar(100),
    [Fringes ] FLOAT,
    [Job family Cluster HC] nvarchar(100),
    [LC-HC] nvarchar(100),
    [New Hire CY] nvarchar(100),
    [Post Tag Facility] nvarchar(100),
    [Post Tag Entity] nvarchar(100),
   [Role Matrix] nvarchar(100),
    [VARPAY-Amount] nvarchar(20),
    [Position ID for Overlapping] nvarchar(100),
    [Position Count for Actual Cost] nvarchar(100),
    [Position Overlapping (Transition)] nvarchar(100),
    [BU for Geographical Selection] nvarchar(100),
    [Job Family Cluster for Geographical Selection] nvarchar(100),
    [Job Family Cluster for Geographical Selection_HC] nvarchar(100),
    [Promo-In Position ID (AOP - FY)] nvarchar(100),
    [Clear Promo (AOP - FY)] nvarchar(100),
    [Simulation Tag (AOP - FY)] nvarchar(100),
    [Select for Simulation (AOP - FY)] nvarchar(100),
    [Position Sub Band (AOP - FY)] nvarchar(100),
    [Start Date (AOP - FY)] DATETIME,
    [Facility Country (AOP - FY)] nvarchar(100),
    [Cost Center (AOP - FY)] nvarchar(100),
    [OTE-(HeadCount Offered) (AOP - FY)] nvarchar(20),
    [Loaded Cost (USD) (AOP - FY)] FLOAT,
    [Cost (AOP - FY)] nvarchar(100),
    [Conditional Formatting Flag (AOP - FY)] nvarchar(100),
    [Counts (AOP - FY)] nvarchar(100),
    [Levers Counts (AOP - FY)] nvarchar(100),
    [AOP Budgeted Cost (AOP - FY)] nvarchar(100),
    [Low Cost - Headcount (AOP - FY)] nvarchar(100),
    [High cost - Headcount (AOP - FY)] nvarchar(100),
    [(Final Country) (AOP - FY)] nvarchar(100),
    [def country (AOP - FY)] nvarchar(100),
    [(Cost Center) (AOP - FY)] nvarchar(100),
    [(Sub Band) (AOP - FY)] nvarchar(100),
    [Budgeted Position (AOP - FY)] nvarchar(100),
    [DFM Low Cost (AOP - FY)] FLOAT,
    [DFM High Cost (AOP - FY)] FLOAT,
    [New Hire Tag (AOP - FY)] nvarchar(100),
    [NH Counts (AOP - FY)] nvarchar(100),
    [NH Cost (AOP - FY)] FLOAT,
    [Growth Business NH Count (AOP - FY)] nvarchar(100),
    [Growth Business NH Cost (AOP - FY)] FLOAT,
    [OTE Local without Increment  CY Exc  Rate (AOP - FY)] nvarchar(100),
    [Benefits Local without Increment  CY Exc  Rate (AOP - FY)] nvarchar(100),
    [Load cost USD without Increment  CY Exc  Rate (AOP - FY)] FLOAT,
    [Cost column without Increment  CY Exc  Rate (AOP - FY)] FLOAT,
    [Local OTE Post Increment%  with  CY Exc Rate (AOP - FY)] nvarchar(100),
    [Benefits Local with Increment  CY Exc  Rate (AOP - FY)] nvarchar(100),
    [Load cost USD  with Increment  CY Exc  Rate (AOP - FY)] FLOAT,
    [Cost column  with Increment  CY Exc  Rate (AOP - FY)] FLOAT,
    [Local OTE Post Increment%  with  FY Exc Rate (AOP - FY)] nvarchar(100),
    [Benefits Local with increment FY Exc  Rate (AOP - FY)] nvarchar(100),
    [Load cost USD with increment FYExc  Rate (AOP - FY)] FLOAT,
    [OTE After Lever (AOP - FY)] nvarchar(100),
    [Benefits After Lever (AOP - FY)] nvarchar(100),
    [Loaded Cost (USD) After Lever (AOP - FY)] FLOAT,
    [AOP FY EXIT HC (AOP - FY)] nvarchar(100),
    [AOP FY EXIT COST (AOP - FY)] FLOAT,
    [AOP FY Count (AOP - FY)] nvarchar(100),
    [AOP FY OTE (AOP - FY)] nvarchar(100),
    [AOP FY Benefits (AOP - FY)] nvarchar(100),
    [NH Band (AOP - FY)] nvarchar(100),
    [AOP FY Year (AOP - FY)] DATETIME,
    [AOP FY Sub Band (AOP - FY)] nvarchar(100),
    [Total Varriable pay (AOP - FY)] nvarchar(100),
    [Basic Salary (AOP - FY)] nvarchar(100),
    [RETRIALS (AOP - FY)] nvarchar(100),
    [Period for Fixed pay (AOP - FY)] nvarchar(100),
    [allowance (AOP - FY)] FLOAT,
    [HRA (AOP - FY)] nvarchar(100),
    [Statutory Bonus (AOP - FY)] nvarchar(100),
    [Fixed Salary (AOP - FY)] nvarchar(100),
    [Promo Changed Sub Band  (AOP - FY)] nvarchar(100),
    [AOP FY Country (AOP - FY)] nvarchar(100),
    [AOP FY Currency (AOP - FY)] nvarchar(100),
    [Band For Fixed Sal IND (AOP - FY)] nvarchar(100),
    [Band For Fixed Sal INT (AOP - FY)] nvarchar(100),
    [%deduction in Variable (AOP - FY)] nvarchar(100),
    [Total varriable pay before lever (AOP - FY)] nvarchar(100),
    [Budgeted CTC after lever (AOP - FY)] FLOAT,
    [Budgeted CTC before lever (AOP - FY)] FLOAT,
    [New Hire CY Cal (AOP - FY)] nvarchar(100),
    [MIS Items (AOP - FY)] nvarchar(100),
    [Position AOP End Date (AOP - FY)] DATETIME,
    [Position AOP Start Date (AOP - FY)] DATETIME,
    [Actual Start Date of Position (AOP - FY)] DATETIME,
    [Post Tag Entity (AOP - FY)] nvarchar(100),
    [Attrition Replacement] nvarchar(100),
    [Final Sub Band of Position (AOP - FY)] nvarchar(100),
    [Employee Sub Band (AOP - FY)] nvarchar(100),
    [International Region (AOP - FY)] nvarchar(100),
    [Revised Quartile (AOP - FY)] nvarchar(100),
    [Local Currency (AOP - FY)] nvarchar(100),
    [OTE (Local Currency) (AOP - FY)] nvarchar(100),
    [Fringes (Local Currency) (AOP - FY)] nvarchar(100),
    [Loaded Cost (Local Currency) (AOP - FY)] FLOAT,
    [Prospective Outlook (CY) USD (AOP - FY)] nvarchar(100),
    [Cost with Lever Intermediary (AOP - FY)] FLOAT,
    [Cost with Lever breakup (AOP - FY)] FLOAT,
    [Unique Code Quartile (AOP - FY)] nvarchar(100),
    [Final End Date (AOP - FY)] DATETIME,
    [Lever Used (AOP - FY)] nvarchar(100),
    [Low Cost - Total cost (AOP - FY)] FLOAT,
    [High Cost - Total cost (AOP - FY)] FLOAT,
    [Parent Country (AOP - FY)] nvarchar(100),
    [DFM Ind  HC (AOP - FY)] nvarchar(100),
    [DFM Int  HC (AOP - FY)] nvarchar(100),
    [Vertical (AOP - FY)] nvarchar(100),
    [Job Level (AOP - FY)] nvarchar(100),
    [OTE After Increment (AOP - FY)] nvarchar(100),
    [OTE (USD) (AOP - FY)] nvarchar(100),
    [Fringes (USD) (AOP - FY)] nvarchar(100),
    [Promo in Employee Subband (AOP - FY)] nvarchar(100),
    [Balanced AOP SLA (AOP - FY)] nvarchar(100),
    [LOB Segment (AOP - FY)] nvarchar(100),
    [BU SSU (AOP - FY)] nvarchar(100)
)


BULK INSERT [dbo].[Simulation_1]
FROM 'D:\binset\Simulation - CY.txt'
WITH
(
FIRSTROW = 2,
FIELDTERMINATOR= '\t',
ROWTERMINATOR = '\n'
)
